md_mongodb:
  container_name: md_mongodb
  hostname: mongodb.md
  net: rxmd
  image: mongo:3.2.0
  volumes:
    - ./data/mongo:/data/db
    - ./etc/mongo:/etc/mongo
  command: -f /etc/mongo/mongodb.conf
  ports:
    - "27018:27018"
